import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Lexend_Deca } from "next/font/google";
import "./globals.css";
import Provider from "./providers";
import Providers from "./providers";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta",
  display: "swap",
});

const lexendDeca = Lexend_Deca({
  subsets: ["latin"],
  variable: "--font-lexend-deca",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sport Fair System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakarta.variable} ${lexendDeca.variable}`}>
        <Providers> {children} </Providers> 
      </body>
    </html>
  );
}
